extern "C" void connect();
extern "C" class Transaction;
extern "C" Transaction* NewTransaction(unsigned long long dateTime, float amt, char * const channel, char * const behavior);
extern "C" unsigned long long TxGetDateTime(Transaction* txPtr);
extern "C" float TxGetAmount(Transaction* txPtr);
extern "C" const char *TxGetChannelPtr(Transaction* txPtr);
extern "C" const char *TxGetBehaviorPtr(Transaction* txPtr);
extern "C" class TransactionList;
//extern "C" TransactionList *NewTransactionList();
extern "C" void *NewTransactionList();
//extern "C" void TxListAppend(TransactionList *txList, Transaction *tx);
extern "C" void TxListAppend(void *txList, Transaction *tx);
//extern "C" Transaction *TxListGetByIndex(TransactionList *txList, int idx);
extern "C" Transaction *TxListGetByIndex(void *txList, int idx);
extern "C" class Rule;
extern "C" Rule* NewRule(float amtThresh_in, int timesThresh);
//extern "C" bool RunRule(Rule* rulePtr, TransactionList *txList, unsigned long long dateTimeStart);
extern "C" bool RunRule(Rule* rulePtr, void *txList, unsigned long long dateTimeStart);
extern "C" float RuleGetAmtThresh(Rule* rulePtr);
extern "C" class RuleA1;
extern "C" Rule* NewRuleA1(float amtThresh_in, int timesThresh);
